#!/bin/bash

get_MIMEtype() {
  
  local file=$1
  file -bi $file || return $?

} 

#GetSensingDate

#GetArchiveContent

#GetCEOSSensingDate

get_Envisat_sensing_date() {
  local dataset="$1"
  res=`sed -b -n "10,10p" $dataset | cut -b 16-26 | xargs -I {} date -d {} +%Y%m%d`
  
  echo $res
}

#GetCSKSensingDate

#GetTSXSensingDate

#GetRadarsatSensingDate

#GetSentinel1SensingDate

#CreateAdoreEnv

#CreateGMTSAREnv

#CreateROIPACEnv

